BEGIN TRANSACTION;
INSERT INTO "restaurant" VALUES (1,'Urban Burger');
INSERT INTO "restaurant" VALUES (2,'Super Stir Fry');
INSERT INTO "restaurant" VALUES (3,'Panda Garden');
INSERT INTO "restaurant" VALUES (4,'Thyme for That Vegetarian Cuisine ');
INSERT INTO "restaurant" VALUES (5,'Tony''s Bistro ');
INSERT INTO "restaurant" VALUES (6,'Andala''s');
INSERT INTO "restaurant" VALUES (7,'Auntie Ann''s Diner ');
INSERT INTO "restaurant" VALUES (8,'Cocina Y Amor ');
INSERT INTO "restaurant" VALUES (9,'State Bird Provisions');

INSERT INTO "menu_item" VALUES ('Veggie burger',1,'Juicy grilled veggie patty with tomato mayo and lettuce','$7.50','Entree',1);
INSERT INTO "menu_item" VALUES ('French Fries',2,'with garlic and parmesan','$2.99','Appetizer',1);
INSERT INTO "menu_item" VALUES ('Chicken Burger',3,'Juicy grilled chicken patty with tomato mayo and lettuce','$5.50','Entree',1);
INSERT INTO "menu_item" VALUES ('Chocolate Cake',4,'fresh baked and served with ice cream','$3.99','Dessert',1);
INSERT INTO "menu_item" VALUES ('Sirloin Burger',5,'Made with grade A beef','$7.99','Entree',1);
INSERT INTO "menu_item" VALUES ('Root Beer',6,'16oz of refreshing goodness','$1.99','Beverage',1);
INSERT INTO "menu_item" VALUES ('Iced Tea',7,'with Lemon','$.99','Beverage',1);
INSERT INTO "menu_item" VALUES ('Grilled Cheese Sandwich',8,'On texas toast with American Cheese','$3.49','Entree',1);
INSERT INTO "menu_item" VALUES ('Veggie Burger',9,'Made with freshest of ingredients and home grown spices','$5.99','Entree',1);
INSERT INTO "menu_item" VALUES ('Chicken Stir Fry',10,'With your choice of noodles vegetables and sauces','$7.99','Entree',2);
INSERT INTO "menu_item" VALUES ('Peking Duck',11,' A famous duck dish from Beijing[1] that has been prepared since the imperial era. The meat is prized for its thin, crisp skin, with authentic versions of the dish serving mostly the skin and little meat, sliced in front of the diners by the cook','$25','Entree',2);
INSERT INTO "menu_item" VALUES ('Spicy Tuna Roll',12,'Seared rare ahi, avocado, edamame, cucumber with wasabi soy sauce ',15,'Entree',2);
INSERT INTO "menu_item" VALUES ('Nepali Momo ',13,'Steamed dumplings made with vegetables, spices and meat. ',12,'Entree',2);
INSERT INTO "menu_item" VALUES ('Ramen',15,'a Japanese noodle soup dish. It consists of Chinese-style wheat noodles served in a meat- or (occasionally) fish-based broth, often flavored with soy sauce or miso, and uses toppings such as sliced pork, dried seaweed, kamaboko, and green onions.',12,'Entree',2);
INSERT INTO "menu_item" VALUES ('Pho',16,'a Vietnamese noodle soup consisting of broth, linguine-shaped rice noodles called banh pho, a few herbs, and meat.','$8.99','Entree',3);
INSERT INTO "menu_item" VALUES ('Chinese Dumplings',17,'a common Chinese dumpling which generally consists of minced meat and finely chopped vegetables wrapped into a piece of dough skin. The skin can be either thin and elastic or thicker.','$6.99','Appetizer',3);
INSERT INTO "menu_item" VALUES ('Gyoza',18,'The most prominent differences between Japanese-style gyoza and Chinese-style jiaozi are the rich garlic flavor, which is less noticeable in the Chinese version, the light seasoning of Japanese gyoza with salt and soy sauce, and the fact that gyoza wrappers are much thinner','$9.95','Entree',3);
INSERT INTO "menu_item" VALUES ('Stinky Tofu',19,'Taiwanese dish, deep fried fermented tofu served with pickled cabbage.','$6.99','Entree',3);
INSERT INTO "menu_item" VALUES ('Veggie Burger',20,'Juicy grilled veggie patty with tomato mayo and lettuce','$9.50','Entree',3);
INSERT INTO "menu_item" VALUES ('Tres Leches Cake',21,'Rich, luscious sponge cake soaked in sweet milk and topped with vanilla bean whipped cream and strawberries.','$2.99','Dessert',4);
INSERT INTO "menu_item" VALUES ('Mushroom risotto',22,'Portabello mushrooms in a creamy risotto','$5.99','Entree',4);
INSERT INTO "menu_item" VALUES ('Honey Boba Shaved Snow',23,'Milk snow layered with honey boba, jasmine tea jelly, grass jelly, caramel, cream, and freshly made mochi','$4.50','Dessert',4);
INSERT INTO "menu_item" VALUES ('Cauliflower Manchurian',24,'Golden fried cauliflower florets in a midly spiced soya,garlic sauce cooked with fresh cilantro, celery, chilies,ginger & green onions','$6.95','Appetizer',4);
INSERT INTO "menu_item" VALUES ('Aloo Gobi Burrito',25,'Vegan goodness. Burrito filled with rice, garbanzo beans, curry sauce, potatoes (aloo), fried cauliflower (gobi) and chutney. Nom Nom','$7.95','Entree',4);
INSERT INTO "menu_item" VALUES ('Veggie Burger',26,'Juicy grilled veggie patty with tomato mayo and lettuce','$6.80','Entree',4);
INSERT INTO "menu_item" VALUES ('Shellfish Tower',27,'Lobster, shrimp, sea snails, crawfish, stacked into a delicious tower','$13.95','Entree',5);
INSERT INTO "menu_item" VALUES ('Chicken and Rice',28,'Chicken... and rice','$4.95','Entree',5);
INSERT INTO "menu_item" VALUES ('Mom''s Spaghetti',29,'Spaghetti with some incredible tomato sauce made by mom','$6.95','Entree',5);
INSERT INTO "menu_item" VALUES ('Choc Full O'' Mint (Smitten''s Fresh Mint Chip ice cream)',30,'Milk, cream, salt, ..., Liquid nitrogen magic','$3.95','Dessert',5);
INSERT INTO "menu_item" VALUES ('Tonkatsu Ramen',31,'Noodles in a delicious pork-based broth with a soft-boiled egg','$7.95','Entree',5);
INSERT INTO "menu_item" VALUES ('Lamb Curry',32,'Slow cook that thang in a pool of tomatoes, onions and alllll those tasty Indian spices. Mmmm.','$9.95','Entree',6);
INSERT INTO "menu_item" VALUES ('Chicken Marsala',33,'Chicken cooked in Marsala wine sauce with mushrooms','$7.95','Entree',6);
INSERT INTO "menu_item" VALUES ('Potstickers',34,'Delicious chicken and veggies encapsulated in fried dough.','$6.50','Appetizer',6);
INSERT INTO "menu_item" VALUES ('Nigiri Sampler',35,'Maguro, Sake, Hamachi, Unagi, Uni, TORO!','$6.75','Appetizer',6);
INSERT INTO "menu_item" VALUES ('Veggie Burger',36,'Juicy grilled veggie patty with tomato mayo and lettuce','$7.00','Entree',6);
INSERT INTO "menu_item" VALUES ('Chicken Fried Steak',37,'Fresh battered sirloin steak fried and smothered with cream gravy','$8.99','Entree',7);
INSERT INTO "menu_item" VALUES ('Boysenberry Sorbet',38,'An unsettlingly huge amount of ripe berries turned into frozen (and seedless) awesomeness','$2.99','Dessert',7);
INSERT INTO "menu_item" VALUES ('Broiled salmon',39,'Salmon fillet marinated with fresh herbs and broiled hot & fast','$10.95','Entree',7);
INSERT INTO "menu_item" VALUES ('Morels on toast (seasonal)',40,'Wild morel mushrooms fried in butter, served on herbed toast slices','$7.50','Appetizer',7);
INSERT INTO "menu_item" VALUES ('Tandoori Chicken',41,'Chicken marinated in yoghurt and seasoned with a spicy mix(chilli, tamarind among others) and slow cooked in a cylindrical clay or metal oven which gets its heat from burning charcoal.','$8.95','Entree',7);
INSERT INTO "menu_item" VALUES ('Veggie Burger',42,'Juicy grilled veggie patty with tomato mayo and lettuce','$9.50','Entree',7);
INSERT INTO "menu_item" VALUES ('Spinach Ice Cream',43,'vanilla ice cream made with organic spinach leaves','$1.99','Dessert',7);
INSERT INTO "menu_item" VALUES ('Super Burrito Al Pastor',44,'Marinated Pork, Rice, Beans, Avocado, Cilantro, Salsa, Tortilla','$5.95','Entree',8);
INSERT INTO "menu_item" VALUES ('Cachapa',45,'Golden brown, corn-based Venezuelan pancake; usually stuffed with queso telita or queso de mano, and possibly lechon. ','$7.99','Entree',8);
INSERT INTO "menu_item" VALUES ('Chantrelle Toast',46,'Crispy Toast with Sesame Seeds slathered with buttery chantrelle mushrooms','$5.95','Appetizer',9);
INSERT INTO "menu_item" VALUES ('Guanciale Chawanmushi',47,'Japanese egg custard served hot with spicey Italian Pork Jowl (guanciale)','$6.95','Dessert',9);
INSERT INTO "menu_item" VALUES ('Lemon Curd Ice Cream Sandwich',48,'Lemon Curd Ice Cream Sandwich on a chocolate macaron with cardamom meringue and cashews','$4.25','Dessert',9);
COMMIT;
